# Generated by Django 4.1.4 on 2023-04-04 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='add_time',
            field=models.DateTimeField(default='2023-04-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='like',
            name='add_time',
            field=models.DateTimeField(default='2023-04-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
