# Generated by Django 4.1.4 on 2023-01-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0003_career_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cname',
            field=models.CharField(max_length=40),
        ),
    ]
