# Generated by Django 4.1.4 on 2023-01-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0004_alter_career_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cdetail',
            field=models.TextField(),
        ),
    ]
