# Generated by Django 4.1.4 on 2023-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0008_career_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='ctitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
