# Generated by Django 4.1.4 on 2023-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0009_career_ctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='ctitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
