# Generated by Django 4.1.4 on 2023-02-09 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Career', '0010_alter_career_ctitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Career1',
        ),
    ]
