# Generated by Django 4.1.4 on 2023-02-09 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Career', '0011_rename_career_career1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career1',
            new_name='Career',
        ),
    ]
