# Generated by Django 4.1.4 on 2023-02-15 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Career', '0012_rename_career1_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('ctitle', models.CharField(blank=True, max_length=100)),
                ('cname', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('cdetail', models.TextField()),
                ('tags', models.TextField(default='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
