# Generated by Django 4.1.4 on 2023-03-21 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Career', '0013_gov'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gov',
            new_name='Career2',
        ),
    ]
