# Generated by Django 4.1.4 on 2023-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0014_rename_gov_career2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cdetail',
            field=models.TextField(blank=True),
        ),
    ]
